preserve_hierarchy: false
files:
  - source: /src/locale/en-US/*
    translation: /src/locale/%two_letters_code%/%original_file_name%
    escape_quotes: 0
    escape_special_characters: 0
    update_option: update_as_unapproved
  - source: /src/locale/en-US/*
    translation: /src/locale/%locale%/%original_file_name%
    escape_quotes: 0
    escape_special_characters: 0
    update_option: update_as_unapproved
